name: 🔄 Build, Test & 🚀 Publish Dexlaris.OpenStreetMap

on:
  push:
    branches: [main, master]
    tags: ['v*']
  pull_request:
    branches: [main, master]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_OUTPUT: ${{ github.workspace }}/nupkgs
  PKG_SOURCE: https://nuget.pkg.github.com/Dexlaris/index.json
  SOLUTION_NAME: Dexlaris.OpenStreetMap.sln

permissions:
  packages: write
  contents: read
  
jobs:
  build-test:
    name: 🔧 Build & ✅ Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore + Build
        run: |
          dotnet restore ${{ env.SOLUTION_NAME }}
          dotnet build ${{ env.SOLUTION_NAME }} --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test ${{ env.SOLUTION_NAME }} --configuration Release --no-build --verbosity normal

  publish:
    name: 📦 Publish NuGet Package
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Extract version number from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        
      - name: Restore & Build
        run: |
          dotnet restore ${{ env.SOLUTION_NAME }}
          dotnet build ${{ env.SOLUTION_NAME }} --configuration Release

      - name: Pack NuGet Package
        run: |
          dotnet pack src/Dexlaris.OpenStreetMap/Dexlaris.OpenStreetMap.csproj \
            --configuration Release \
            --output ${{ env.NUGET_OUTPUT }} \
            -p:PackageVersion=$VERSION

      - name: Authenticate to GitHub Packages
        run: dotnet nuget add source --username Dexlaris --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Dexlaris/index.json"

      - name: Push Package(s)
        run: |
          for file in ${{ env.NUGET_OUTPUT }}/*.nupkg; do
            dotnet nuget push "$file" --source "github" --skip-duplicate
          done
          